# Generated by the release workflow of https://github.com/whaledoc/whaledoc-cli. Don't edit it by hand:
# changes are overwritten by the next release.
class Whaledoc < Formula
  desc "Official command-line interface for WhaleDoc"
  homepage "https://whaledoc.io"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/whaledoc/whaledoc-cli/releases/download/v0.1.1/whaledoc-macos-arm64.tar.gz"
      sha256 "000f7a3d34c0c7b6e8d0d328bac3e87fa62f236e0ee70f0a3426aaf363c3f329"
    end

    on_intel do
      url "https://github.com/whaledoc/whaledoc-cli/releases/download/v0.1.1/whaledoc-macos-x64.tar.gz"
      sha256 "d92ec6bae67d33c938db5ca21a1e40216a36442b6b613fbec7991e9ad49aa8f3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/whaledoc/whaledoc-cli/releases/download/v0.1.1/whaledoc-linux-arm64.tar.gz"
      sha256 "70574057f7a996dd4070a38bbbabf1ea1c1c7030d574df3d76b24018596d868a"
    end

    on_intel do
      url "https://github.com/whaledoc/whaledoc-cli/releases/download/v0.1.1/whaledoc-linux-x64.tar.gz"
      sha256 "ae0b9b5a0ce0d35815ec2b513e2da9b6ca172aa99fe04067572b79a1eefc1fc4"
    end
  end

  def install
    bin.install "whaledoc"
  end

  test do
    assert_match "WhaleDoc version #{version}", shell_output("#{bin}/whaledoc --version")
  end
end
