# Generated by the release workflow of https://github.com/whaledoc/whaledoc-cli. Don't edit it by hand:
# changes are overwritten by the next release.
class Whaledoc < Formula
  desc "Official command-line interface for WhaleDoc"
  homepage "https://whaledoc.io"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/whaledoc/whaledoc-cli/releases/download/v0.2.0/whaledoc-macos-arm64.tar.gz"
      sha256 "acb3befa823618698bbd95cc8ae76090b8a9e1f9578ca9b7692e5060ce2da2ce"
    end

    on_intel do
      url "https://github.com/whaledoc/whaledoc-cli/releases/download/v0.2.0/whaledoc-macos-x64.tar.gz"
      sha256 "d30c34ba0245fe86fdc35afa2178fe7777998d59844f6c28b74b120be193e41b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/whaledoc/whaledoc-cli/releases/download/v0.2.0/whaledoc-linux-arm64.tar.gz"
      sha256 "49473a1399fe5c9c09d49d9267f291f401a089ce04b9a407cc34cadebb16026f"
    end

    on_intel do
      url "https://github.com/whaledoc/whaledoc-cli/releases/download/v0.2.0/whaledoc-linux-x64.tar.gz"
      sha256 "a76b99439c72e57661fabfb05f4e2d02102811659a838113b642fcd2dd29176e"
    end
  end

  def install
    bin.install "whaledoc"
  end

  test do
    assert_match "WhaleDoc version #{version}", shell_output("#{bin}/whaledoc --version")
  end
end
